// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3W8fuQIbzyX9GZqJf7XtwwJKNQroRV2g',
    appId: '1:697873064948:web:51d4928ec9a9ae15e28fa1',
    messagingSenderId: '697873064948',
    projectId: 'glamapp-e8387',
    authDomain: 'glamapp-e8387.firebaseapp.com',
    storageBucket: 'glamapp-e8387.firebasestorage.app',
    measurementId: 'G-K98LB1TH06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDngCv_v_Cg4uZ4B7gbXx1_EgZciQOeCfQ',
    appId: '1:697873064948:android:6c257312fd3446e0e28fa1',
    messagingSenderId: '697873064948',
    projectId: 'glamapp-e8387',
    storageBucket: 'glamapp-e8387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgwUawmlIVKQSCq5BBOONG9Oi9tpDwEPg',
    appId: '1:697873064948:ios:40e9924080771142e28fa1',
    messagingSenderId: '697873064948',
    projectId: 'glamapp-e8387',
    storageBucket: 'glamapp-e8387.firebasestorage.app',
    iosBundleId: 'com.example.myDailyGlam',
  );
}
